# NumPy

In [1]:
import numpy as np

## NumPy arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).
### Create NumPy arrays
<b>array():</b> creates numpy array from Python list.

In [3]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods
<b>arange():</b> returns evenly spaced values within a given interval. 

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

<b>zeros():</b> generates arrays of zeroes.

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b>ones():</b> generates arrays of ones.

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<b>linspace():</b> returns evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

<b>eye():</b> creates an identity matrix.

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
<b>rand():</b> creates an array of the given shape and populate it with random samples from a uniform distribution over `[0, 1)`.

In [17]:
np.random.rand(2)

array([0.16696941, 0.09942028])

In [18]:
np.random.rand(5, 5)

array([[0.89884113, 0.17480837, 0.70077743, 0.81635913, 0.85369203],
       [0.88737112, 0.88124211, 0.45545817, 0.6562209 , 0.09674378],
       [0.7826782 , 0.98454522, 0.67361438, 0.86375126, 0.22370184],
       [0.09039533, 0.42478756, 0.93731692, 0.72522562, 0.93306831],
       [0.1254793 , 0.13075762, 0.0508365 , 0.89581731, 0.75664163]])

<b>randn():</b> returns a sample (or samples) from the "standard normal" distribution, unlike `rand()` which is uniform.

In [19]:
np.random.randn(2)

array([-0.44112459,  0.20242855])

In [20]:
np.random.randn(5, 5)

array([[ 0.39240721,  0.0501354 , -0.43332687, -0.60025723,  1.35289551],
       [ 0.67377838, -1.02711328,  0.19407257, -1.76691955, -0.45317547],
       [-0.84465526, -0.96398099,  0.09135385, -0.38416747, -0.79869548],
       [-1.05117617, -0.53290644,  0.56268593, -0.39378919, -1.64919907],
       [-0.4856161 ,  0.42134704,  0.65872051,  1.11874129, -1.36640596]])

<b>randint():</b> returns random integers from "low" (inclusive) to "high" (exclusive).

In [21]:
np.random.randint(1, 100)

76

In [22]:
np.random.randint(1, 100, 10)

array([34, 15,  3, 85,  4, 98, 74,  5,  5, 25])

### Array attributes and methods