# NumPy

In [1]:
import numpy as np

## NumPy arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).
### Create NumPy arrays
<b>array():</b> creates numpy array from Python list.

In [3]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods for number generation
<b>arange():</b> returns evenly spaced values within a given interval. 

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

<b>zeros():</b> generates arrays of zeroes.

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b>ones():</b> generates arrays of ones.

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<b>linspace():</b> returns evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

<b>eye():</b> creates an identity matrix.

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
<b>rand():</b> creates an array of the given shape and populate it with random samples from a uniform distribution over `[0, 1)`.

In [17]:
np.random.rand(2)

array([0.16696941, 0.09942028])

In [18]:
np.random.rand(5, 5)

array([[0.89884113, 0.17480837, 0.70077743, 0.81635913, 0.85369203],
       [0.88737112, 0.88124211, 0.45545817, 0.6562209 , 0.09674378],
       [0.7826782 , 0.98454522, 0.67361438, 0.86375126, 0.22370184],
       [0.09039533, 0.42478756, 0.93731692, 0.72522562, 0.93306831],
       [0.1254793 , 0.13075762, 0.0508365 , 0.89581731, 0.75664163]])

<b>randn():</b> returns a sample (or samples) from the "standard normal" distribution, unlike `rand()` which is uniform.

In [19]:
np.random.randn(2)

array([-0.44112459,  0.20242855])

In [20]:
np.random.randn(5, 5)

array([[ 0.39240721,  0.0501354 , -0.43332687, -0.60025723,  1.35289551],
       [ 0.67377838, -1.02711328,  0.19407257, -1.76691955, -0.45317547],
       [-0.84465526, -0.96398099,  0.09135385, -0.38416747, -0.79869548],
       [-1.05117617, -0.53290644,  0.56268593, -0.39378919, -1.64919907],
       [-0.4856161 ,  0.42134704,  0.65872051,  1.11874129, -1.36640596]])

<b>randint():</b> returns random integers from "low" (inclusive) to "high" (exclusive).

In [21]:
np.random.randint(1, 100)

76

In [22]:
np.random.randint(1, 100, 10)

array([34, 15,  3, 85,  4, 98, 74,  5,  5, 25])

### Array attributes and methods

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([ 5, 34, 45, 31, 19, 22, 37, 28, 14,  2])

### Reshape
<b>reshape():</b> returns an array containing the same data with a new shape.

In [27]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

In [28]:
ranarr

array([ 5, 34, 45, 31, 19, 22, 37, 28, 14,  2])

<b>max()</b>

In [29]:
ranarr.max()

45

<b>argmax():</b>

In [31]:
ranarr.argmax()

2

<b>min()</b>

In [30]:
ranarr.min()

2

<b>argmin():</b>

In [32]:
ranarr.argmin()

9

### Shape
<b>shape:</b> an attribute that arrays have (not a method).

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1, 25).shape

(1, 25)

In [36]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25, 1).shape

(25, 1)

### Data type
<b>dtype:</b> you can also grab the data type of the object in the array.

In [38]:
arr.dtype

dtype('int64')

## NumPy indexing & selection

In [2]:
# Create sample array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket indexing & selection

In [3]:
# Get a value at an index
arr[8]

8

In [4]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting
NumPy arrays differ from a normal Python list because of their ability to broadcast.

In [6]:
# Set a value with index range (broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
# Reset array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
# Change slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [10]:
# Note the changes also occur in the original array.
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
# To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Index a 2D array (matrices)
The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>.

In [12]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
# Index row
arr_2d[1]

array([20, 25, 30])

In [14]:
# Get individual element value
arr_2d[1][0]

20

In [15]:
# Get individual element value
arr_2d[1, 0]

20

In [16]:
# Shape (2, 2) from top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [17]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [18]:
arr_2d[2, :]

array([35, 40, 45])

### Conditional selection

In [20]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## NumPy operations

### Arithmetic

In [28]:
# A sample array
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# Warning on division by zero, but not an error
# Just replaced with nan
arr / arr

/home/yungshun/.virtualenvs/yungshun-py3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
# Also warning but not an error instead infinity
1 / arr

/home/yungshun/.virtualenvs/yungshun-py3/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [34]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal array functions
<b>sqrt():</b> takes square roots.

In [35]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

<b>exp():</b> calculates exponential.

In [36]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

<b>max():</b> same as arr.max().

In [37]:
np.max(arr)

9

<b>sin():</b>

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

<b>log():</b>

In [39]:
np.log(arr)

/home/yungshun/.virtualenvs/yungshun-py3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])